### ISSUE TITLE
Duo:  Logs contain escaped "/"?

### ISSUE THREAD

**Issue by CH-KeithMo** [ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API#15]
Logs seem to be escaping the double quote inside of a nested element.  Example Payload, Sanitized:  Had to edit to show code.

`{"action":"admin_send_reset_password_email","description":"{\"phone\": \"+13039072014\", \"name\": \"John Doe\", \"email\": \"john.doe@mydomain.tld\", \"hardtoken\": null}","isotimestamp":"2020-11-04T10:10:10+00:00","object":null,"timestamp":1604484610,"username":"John Doe"}`

**Comment by kdegrace** [comment]
The JSON object looks well-formed but note that the "description" field contains a JSON document encoded as a string inside of it.  That's where the escapes are coming from.

Which REST API is this coming from?  Is that what they are returning from as a response, or have you done some manipulation?

**Comment by CH-KeithMo** [comment]
Nope, I have not made any changes.  But I did notice this on our QRadar as well as a newly configured LS for another customer.

**Comment by kdegrace** [comment]
Interesting.  In my comment, I didn't realize you were talking about Duo.  I had just assumed you were working on a new workflow.

If I look at the Duo API documentation (https://duo.com/docs/adminapi#administrator-logs), it is clearly what they are returning as a response:
![image](https://user-images.githubusercontent.com/32196820/98257709-61007300-1f56-11eb-985a-8161f7fe1263.png)

There is a way to unescape the description field, assuming this would be the correct behavior.

It will require a bit of investigation.

**Comment by CH-KeithMo** [comment]
Thanks!  Do you need anything from me on this?  My sample payload in the first comment shows the top level values un-escaped just as your screenshot does.

**Comment by kdegrace** [comment]
Turns out this is a bug.  The intention is to always unescape JSON (recursively) whenever possible.  I've discovered a case where this is not happening.

I'll create an internal work item and get this fixed for the next version of the protocol.  I'm not yet sure when this next release will be going out but I have 2-3 items so far to be included so it's gaining weight.

**Comment by CH-KeithMo** [comment]
@kdegrace Just checking in to see if you had some progress here?  We have a few customers now using this but we can not accurately parse the properties with JSON for now.

**Comment by kdegrace** [comment]
I have an internal work item for this, and whatever I come up with will go into the next release of the protocol. However, there is no tentative date for the release yet. I am sure it won't be until 2021. Likely in Q1 somewhere.

I do have a simple workaround for you, if you would like to try it.

Instead of using PostEvents, use a ForEach on the events and post them individually with PostEvent. That will, in effect, "jiggle the wires" and trigger the automatic JSON parse code.  Functionally, it will be identical.

So instead of this:
```
<PostEvents path="/admin_logs/response/body/response" source="${/host}" />
```
try this
```
<ForEach item="/admin_log_event" items="/admin_logs/response/body/response">
    <PostEvent path="/admin_log_event" source="${/host}" />
</ForEach>
```

**Comment by CH-KeithMo** [comment]
Sorry, did not see your update.  I gave this a shot.  Disabled the log source, modified the xml and saved, then enabled the log source.  My test DUO attempts were still escaped in the payload.  I then tried a restart of ecs-ec-ingress (it is our internal server) just to get that all reloaded - no luck.

I also emailed about an unrelated matter and see that you are OoO until the new year.  Have a great New Year!
